### ISSUE TITLE
Crash on attempt to open level, PS Vita 1000, 3.65

### ISSUE THREAD

**Issue by JRHJ510** [hatoving/gdash-vita#2]
After following all instructions and launching the game, I get an error of 
"Unknown symbol "_ZN4FMOD14ChannelControl10getNumDSPsEPi" (0x98a87b20)."

**Comment by JRHJ510** [comment]
Also happens when messing with certain menu items.

**Comment by hatoving** [comment]
https://cdn.discordapp.com/attachments/1199734916401864845/1199734983212933120/gdash.vpk?ex=65c39f45&is=65b12a45&hm=905fd503e7d1da9db0a9b39bac66830812bc3c53cf4af2ffd6e5ace38582f202&

Try this.

**Comment by JRHJ510** [comment]
> https://cdn.discordapp.com/attachments/1199734916401864845/1199734983212933120/gdash.vpk?ex=65c39f45&is=65b12a45&hm=905fd503e7d1da9db0a9b39bac66830812bc3c53cf4af2ffd6e5ace38582f202&
> 
> Try this.



> https://cdn.discordapp.com/attachments/1199734916401864845/1199734983212933120/gdash.vpk?ex=65c39f45&is=65b12a45&hm=905fd503e7d1da9db0a9b39bac66830812bc3c53cf4af2ffd6e5ace38582f202&
> 
> Try this.

This specific error does not appear with this vpk, but a new error does appear, this time the error is 
"Unknown symbol "_ZN4FMOD14ChannelControl9removeDSPEPNS_3DSPE" (0x98a87b24)."

**Comment by JRHJ510** [comment]
> https://cdn.discordapp.com/attachments/712548851248005140/1199744727914922044/gdash.vpk?ex=65c3a859&is=65b13359&hm=d8f6350f9fccea8cf2bd38a30294a7ba897e5ec70cd077f1a3dd4012596cb382&
> 
> How about this?

Error fixed again, but new error takes its place
"Unknown symbol "_ZN4FMOD3DSP7releaseEv" (0x98a87b28)."

**Comment by hatoving** [comment]
https://cdn.discordapp.com/attachments/712548851248005140/1199747551579078796/gdash.vpk?ex=65c3aafa&is=65b135fa&hm=29b035eee77f182af66e10871219fa28a3785985c791391aa370cef0281d2f17&

I have a feeling this isn't the best way to do this lol
Oh well. Try this.

**Comment by JRHJ510** [comment]
> https://cdn.discordapp.com/attachments/712548851248005140/1199747551579078796/gdash.vpk?ex=65c3aafa&is=65b135fa&hm=29b035eee77f182af66e10871219fa28a3785985c791391aa370cef0281d2f17&
> 
> I have a feeling this isn't the best way to do this lol Oh well. Try this.

After all of that troubleshooting, this one works! Thanks, I will continue to test it

**Comment by hatoving** [comment]
Awesome! I'll push the changes to the repo then. I'll close this for now.
